# Generated by Django 3.0.8 on 2022-07-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_score_date',
        ),
        migrations.AddField(
            model_name='user',
            name='doctor_flag',
            field=models.BooleanField(default=False),
        ),
    ]
