# Generated by Django 3.0.8 on 2022-07-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220725_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='eng_name',
            field=models.CharField(choices=[('moles', 'Moles'), ('nevi', 'Nevi'), ('melanoma', 'Melanoma'), ('nail-disease', 'Nail Disease'), ('nail-fungus', 'Nail Fungus'), ('acne', 'Acne'), ('rosacea', 'Rosacea'), ('actinic-keratosis', 'Actinic Keratosis'), ('atopic-dermatitis', 'Atopic Dermatitis'), ('bacteria-infection', 'Bacteria Infection'), ('basal-cell', 'Basal Cell'), ('biting-insect', 'Biting Insect'), ('bullous', 'Bullous'), ('dermatofibroma', 'Dermatofibroma'), ('eczema', 'Eczema'), ('hemangloma', 'Hemangloma'), ('herpes', 'Herpes'), ('keratoses', 'Keratoses'), ('lichen-planus', 'Lichen Planus'), ('lupus', 'Lupus'), ('psoriasis', 'Psoriasis'), ('tinea', 'Tinea'), ('vasculitis', 'Vasculitis'), ('warts', 'Warts')], max_length=30),
        ),
    ]
