# Generated by Django 3.0.8 on 2022-07-13 15:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220712_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmedia',
            name='condition',
        ),
        migrations.AlterField(
            model_name='answermedia',
            name='img',
            field=models.ImageField(blank=True, upload_to=api.models.answer_media_path),
        ),
        migrations.AlterField(
            model_name='conditionmedia',
            name='img',
            field=models.ImageField(blank=True, upload_to=api.models.condition_media_path),
        ),
        migrations.AlterField(
            model_name='questionmedia',
            name='img',
            field=models.ImageField(blank=True, upload_to=api.models.question_media_path),
        ),
    ]
